### PR TITLE
Restore gutter pointer

### PR DESCRIPTION
**Pull request by toolness**
The gutter pointer is back!

Before 1c50dcc41d0b28123e8683072c58c5eeb02aebf2 we had a pointer, but it only worked on lines that didn't wrap, so we removed it (see mozilla/webpagemaker#335). The production branch currently looks like this now:

But this pull request contains an SVG-based one that looks like this for lines that don't wrap:

And this for lines that do wrap:

For reference, see Jess' original [gutter pointer mockup](http://www.flickr.com/photos/jessicaklein/7221327312).

### CODE REVIEW

**Comment by iamjessklein** [comment]
this looks much better.

**Comment by toolness** [comment]
Thanks Jess!

@Pomax, can you take a look at this?

**Comment by Pomax** [comment]
Like it!

One question: do we need to do the dedicated generation based on the block dimensions? We might be able to reduce this code by using a "fixed size" (read: viewbox) SVG image instead, and then apply it with height: 100%, so that we don't have to use generator JS. I don't know if IE8- can do  but I know IE9 will happily render it like any other browser, so it would probably work as a CSS image too.

**Comment by toolness** [comment]
Hmm, good point. I was looking into a CSS solution, actually, but I had some weird problems making the gutter extend into the editor area a bit... How about if we commit this for now, but file a bug to convert it into a pure CSS solution?

**Comment by Pomax** [comment]
yeah, that works for me. I think last time I ended up doing it with relative positioning and a negative right or right-margin value (not sure which now).

**Pull request merged**
