### PR TITLE
Structured require dependency

### PR DESCRIPTION
**Pull request by smagch**
Related to require build optimization issue.
https://github.com/mozilla/webpagemaker/issues/430

Nested require call going to make difficult to optimize. What I've done is
- make vendor libs require dependencies; jquery, underscore, backbone.
- use require.js version 2.x; since version 2.x can handle vendor libs without plugin.
- make less dependencies in main.js; move to module's dependencies if possible.
- extract appReady from main to own file.

I'm going to write r.js build script from now.

NOTE: I forked friendlycode repo and don't use webpagemaker, because I've got a trouble with my network connection: I can't use git protocol! Terrible! I'm asking to my landlord if I can change port settings... :(

### CODE REVIEW

**Comment by smagch** [comment]
mozilla/webpagemaker#430

**Comment by smagch** [comment]
I merged to my gh-pages and add some additional html for convenience.
1. no optimization http://smagch.github.com/friendlycode/
2. requireJS optimized http://smagch.github.com/friendlycode/optimized.html
3. requireJS optimized but no minification http://smagch.github.com/friendlycode/optimized-unminified.html
4. currently Qunit is failing http://smagch.github.com/friendlycode/test

**Comment by smagch** [comment]
I updated my forked repo's gh-pages and now it passes test!

**Comment by jrburke** [comment]
@smagch why did you modify js/main.js from this style:

``` javascript
define(function(require) {
    var a = require('a'),
        b = require('b'),
        c = require('c');
});
```

to this style:

``` javascript
define(['a', 
    'b', 
    'c'], 
function (a, b, c) {});
```

I find the original style clearer/more compact to read. It is what I recommend for long dependency lists like this, if the local variables need to be used.

In addition, the mainConfigFile option:
https://github.com/jrburke/r.js/blob/master/build/example.build.js#L27

should mean you can avoid duplicating the shim config in the build js file, and maybe just get it down to a simpler build profile.

While it is probably not worth redoing this pull request, if the code has moved to webpagemaker, just some feedback for future reference.

**Comment by smagch** [comment]
Thanks for the review @jrburke ! I'm thrilled to get a code review from czar of AMD :)

> It is what I recommend for long dependency lists like this, if the local variables need to be used.

Ah, I did't know that it's recommended to do nested require style. Because I found it's hard to optimize while it's readability is a lot better with nested require call.
Of cause I can optimize with [findNestedDependencies](https://github.com/jrburke/r.js/blob/master/build/example.build.js#L230-235) option. But I think `nested require` is for conditional loading: for example, when a user click a button, load plugin.

If there is no conditional loading, optimized scripts can be used with [almod.js](https://github.com/jrburke/almond), right?
Although @pauirish tweeted recently http://twitter.com/paul_irish/status/213387312829181953

> require.js should never be used in production.

if it has nested require, require.js can be used in production for the conditional loading.

What do you think about at this point, @jrburke ?

> In addition, the mainConfigFile option:

Exactly. I'm currently doing dirty copy and paste because I didn't work out correctly.
https://github.com/smagch/friendlycode/blob/d1c47021a67278a12a0226a3300e59efdef279fe/build-require.js#L45-48
It try to load `js/js/main.js` because it override baseUrl jrburke/r.js#130
I think I can solve the problem with moving config to JSON file somewhere.

I think `r.js` should be used from command line so that I can optimize with Makefile without writing script.
But I alway end up with writing build scripts.

> While it is probably not worth redoing this pull request

I'm very disappointed to hear that :(
it would be grateful if this is going to be a little bit of help when @toolness start working on optimization.

**Comment by smagch** [comment]
Ah, I tried to reduce `main.js`'s dependencies. And I assigned template dependencies to module.
Thinking about it now, it's better to leave as it is: set templates as a option.

**Comment by jrburke** [comment]
> Ah, I did't know that it's recommended to do nested require style. Because I found it's hard to optimize while it's readability is a lot better with nested require call.
> Of cause I can optimize with findNestedDependencies option. But I think nested require is for conditional loading: for example, when a user click a button, load plugin.

findNestedDependencies is only for finding nested callback-style require calls, since those are generally dynamically determined loads that should not be inlined in a build:

``` javascript
define(function(require) {
    require(['b'], function(b){});
});
```

The require('a') form is the expected [sugared form](http://requirejs.org/docs/whyamd.html#sugar) for AMD, and those are always found during the optimization, no need for findNestedDependencies.

> If there is no conditional loading, optimized scripts can be used with almod.js, right?

Conditional loading works with almond.js as long as any possible conditional matched module is included in the build with almond.

> Although @pauirish tweeted recently http://twitter.com/paul_irish/status/213387312829181953
>    require.js should never be used in production.
> if it has nested require, require.js can be used in production for the conditional loading.

Correct, twitter is bad for advice, as it is so short, and Paul got lots of replies about the need for dynamic loading even after a build for very large sites. For many sites, just a single "main" build is needed and almond is just enough for that case. Often for beginners using AMD, these are the sites they run, and I believe that is who Paul was trying to address.

>    In addition, the mainConfigFile option:
> Exactly. I'm currently doing dirty copy and paste because I didn't work out correctly.
> https://github.com/smagch/friendlycode/blob/d1c47021a67278a12a0226a3300e59efdef279fe/build-require.js#L45-48
> It try to load js/js/main.js because it override baseUrl jrburke/r.js#130
> I think I can solve the problem with moving config to JSON file somewhere.

Ah yes. Hopefully you can remove the baseUrl from there and use all the paths/shim config from the mainConfigFile too, and then in that case, hopefully it just works.

> >    While it is probably not worth redoing this pull request
> > I'm very disappointed to hear that :(
> > it would be grateful if this is going to be a little bit of help when @toolness start working on optimization.

Ah sorry, I was going off your original comment and I thought it implied that this repo was superceded by the webmaker code. However, I actually do not know what the code relationships are, so I may have spoken incorrectly there.

If a redone commit is desired for those changes, I suggest starting fresh so that the number of commits and diffs are smaller though, just for git history/ease of comprehension. But again, I'm speaking for what I would expect from my repos so I may not have that right either here.

**Comment by smagch** [comment]
> The require('a') form is the expected sugared form for AMD

I didn't know that fantastic suger!! I've been using require.js for a quite a while. I've been missing really important point.
Thank you @jrburke 

> Ah yes. Hopefully you can remove the baseUrl from there and use all the paths/shim config from the mainConfigFile too, and then in that case, hopefully it just works.

There is still a problem on baseUrl. It seems baseUrl is resolved based on main's path.
https://github.com/jrburke/r.js/blob/2.0.2/build/jslib/build.js#L814
when I remove baseUrl from the build script, `baseUrl` is still `*/js/js/main`.
So I'm going to suggest

``` javascript
build.makeAbsConfig(mainConfig, mainConfigPath);
```

to be

``` javascript
build.makeAbsConfig(mainConfig, absFilePath);
```

And it works in my environment though I have no idea how it would impact in another use case.

> If a redone commit is desired for those changes, I suggest starting fresh

Yeah, it won't takes time. I'm going to restart a branch afterward and make this a clean pull-request.

**Pull request closed without merging**
