### PR TITLE
Redo "set up Ubuntu Mono as code editor font"

### PR DESCRIPTION
**Pull request by joanrieu**
Somehow the Ubuntu Mono font distributed with the editor didn't look as sharp as it does on the Ubuntu website. (Maybe only when the user doesn't have it on his system, which is my case? I haven't had the opportunity to test it.)

The original font looks better than the embedded one.

I partially reverted the commit that introduced the font (I removed the files) to instead make use of Google's Web Fonts service which distributes that font.

This change has the two following advantages:
- It fixes the problem shown above.
- It removes load from the server by using Google's one.

### CODE REVIEW

**Comment by Pomax** [comment]
What OS/Browser combination were you using? I don't see a difference between the reference on font.ubuntu.com and how the fonts render in current public Chrome and Firefox...

**Comment by Pomax** [comment]
(I tried those two on OS X and Win7)

**Comment by Pomax** [comment]
Also, the google web font screenshot you added seems too thin compared to what font.ubuntu.com generates for the monospace version. Did you apply a custom weight? (basically it looks different from "real" ubuntu mono).

**Comment by joanrieu** [comment]
http://font.ubuntu.com/ uses the following code:

``` html
<link href="http://fonts.googleapis.com/css?family=Ubuntu+Mono:400,400italic,700,700italic&amp;subset=latin,greek,cyrillic" rel="stylesheet" type="text/css" />
```

I don't really know what GWF uses as default subset but I supposed it would be "good enough", so I dropped the end of the line (feel free to add it again, I'm really no font/i18n expert):

``` html
<link href="http://fonts.googleapis.com/css?family=Ubuntu+Mono:400,400italic,700,700italic" rel="stylesheet" type="text/css" />
```

Also, we don't need the italic version here, do we?

``` html
<link href="http://fonts.googleapis.com/css?family=Ubuntu+Mono:400,700" rel="stylesheet" type="text/css" />
```

But 400 = regular (r) and 700 = bold (b), so this gives the same result:

``` html
<link href="http://fonts.googleapis.com/css?family=Ubuntu+Mono:r,b" rel="stylesheet" type="text/css" />
```

This is what I put in my commit:

``` html
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Ubuntu+Mono:r,b">
```

**Comment by joanrieu** [comment]
To answer your question, my screenshot was made on Arch Linux using Firefox 14.0.1 (the most recent stable release).

**Comment by Pomax** [comment]
can you rebase (we had some refactoring) and we can merge this in. If this looks better, it looks better.

**Comment by joanrieu** [comment]
In case you missed it, I rebased a week ago (I should have commented to bump the PR, but forgot to).
Tell me if things have changed again since last week and another rebase is needed.

**Comment by Pomax** [comment]
after discussion, we're going to stick with the webmaker.org hosted font, as it looks the same as the ubuntu-hosted font, and allows us to keep our resources local.

**Pull request closed without merging**
