### PR TITLE
Move third-party code into a vendor directory

### PR DESCRIPTION
**Pull request by toolness**
This pull request isn't finished yet, but once it's done, it will resolve #166.

### CODE REVIEW

**Comment by toolness** [comment]
I still need to move jQuery, backbone, lscache, underscore, and require into the vendor directory, as well as the plugins tipsy (jQuery) and i18n and text (require).

While `backbone-events.js` and `jquery.no-conflict.js` aren't technically third-party code, they're just trivial shims atop third-party code, so I should probably move those too.

I'd like to move `inline-l10n.js` into the vendor directory because it's a completely standalone and documented module with no dependencies, but because it's not formally a separate project or anything, I'm not sure if I should.

**Comment by toolness** [comment]
Ok, I think this is good to go, @stenington !

**Comment by stenington** [comment]
To me `vendor/` is a big red flag that says "Don't change code in here; if you need to change it, find the project, contribute your change, then pull down the updated project." So I agree that `inline-l10n.js` shouldn't move in until it has its own repo, and I'd probably even stumble over the shims being in `vendor/` if I thought one of them needed changing. But I'm not sure everyone else' understanding of it is necessarily so strict so I'm not going to claim the shims have to be moved out.

That point aside, the changes look sound to me.

**Comment by toolness** [comment]
Hmm, that's a good point, so I moved the shims from `vendor/` into a new `js/shims/` directory in 4e164eb. Thanks!

**Pull request merged**
