### PR TITLE
Allow Friendlycode embedders to provide alternate publisher backends and allow JS.

### PR DESCRIPTION
**Pull request by toolness**
This will allow us to have an experimental JS-enabled Thimble for MozFest.

### CODE REVIEW

**Comment by toolness** [comment]
You can play around with this here:

http://toolness.github.com/friendlycode/examples/alternate-publisher.html

The example actually publishes to Hackasaurus' publishing endpoint, [hackpub](https://github.com/hackasaurus/hackpub).

**Comment by toolness** [comment]
@Pomax, can you take a quick look at this?

**Comment by Pomax** [comment]
Nice! This looks pretty good; should we percolate that setting down to slowparse too, or do we want to keep it independent and simply say "if you want to use a slowparse that doesn't forbid JS through its treeinspector, make sure to checkout a version that does that"?

**Comment by toolness** [comment]
Rad! Hmm, so slowparse actually doesn't forbid JS by default--it's only if you pass in `TreeInspectors.forbidJS` in the array as a third parameter to `Slowparse.HTML()` that it enables it. So this is already supported by Slowparse... I just wanted to provide an easy way for embedders to revert the default behavior of Friendlycode. Does that make sense?

**Comment by Pomax** [comment]
Yup, great stuff! (post-merge, but worth mention =D)

**Pull request merged**
