### PR TITLE
Relocator refactoring

### PR DESCRIPTION
**Pull request by toolness**
This should fix #8, as well as resolve #33.

Because it fixes #8, I suppose it's not strictly a refactoring, but actually a bug-fix as well.

### CODE REVIEW

**Comment by Pomax** [comment]
The "where is the hint/error" pointer points to the left of the error or hint string right now. Is there a way we can center the arrow on it instead? Also, for errors, we may have two components: 1) the erroneous element and 2) its matching element. For instance, &lt;h1&gt;lalala&lt;/h2&gt; will mark the 'h2' as error, matches to the non-error 'h1'. However, the error message will now point at h1 as if the error should be fixed there.

**Comment by Pomax** [comment]
closes https://github.com/mozilla/webpagemaker/issues/338 when landed

**Comment by Pomax** [comment]
I also left a comment on the gutter arrow. We can make this look full height without stripping the image, we just need a higher res image and background-size

**Comment by toolness** [comment]
Regarding your comments [here](https://github.com/toolness/friendlycode/pull/79#issuecomment-6205126) and [here](https://github.com/toolness/friendlycode/commit/1c50dcc41d0b28123e8683072c58c5eeb02aebf2), good points--do you mind if I merge this pull request now and make separate bugs out of your comments, then fix them in a separate pull request?

**Comment by Pomax** [comment]
we have issues open for those two things, I am okay with merging this pull and then fixing those issues in their respective existing tickets.

**Pull request merged**
